version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend/Dockerfile.frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '5173:5173'

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - .:/app
    ports:
      - '4040:4040'
    env_file:
      - .env