# ┌────────── Etapa 1: Construcción del frontend con Vite ──────────────────────────────┐
FROM node:18-slim AS frontend
WORKDIR /app/frontend

# Desactivar validación SSL
RUN npm config set strict-ssl false

# Copiar solo package.json para cacheo de dependencias
COPY frontend/package.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del frontend
COPY frontend/ ./
RUN npm run build

